### ISSUE TITLE
Setting ai_insert to false requires script to be triggered three times

### ISSUE THREAD

**Issue by rpgaleksy** [Neutronic/ReaScripts#1]
Hi,

I have downloaded the "_Show track or take envelope for last touched parameter_" script and realized that in order to show the envelope, it adds an automation item to the track.
When setting `local ai_insert = false` the creation of an automation item should be omitted, but instead, the action needs to be performed three times in order to take effect as I would want it to.

Not sure why the script would behave that way.. I would appreciate it if you could take a look at that.

**Comment by Neutronic** [comment]
Hey there and thanks for the report. I've just uploaded v1.**03** that fixes the issue.

**Comment by rpgaleksy** [comment]
Works great, thanks!
